### ISSUE TITLE
Open project in Lyo Designer

### ISSUE THREAD

**Issue by Krusty84** [oslc-op/sysml-oslc-server#31]
Hi Dear Team,
I tried to open project in Lyo Designer (4.0) but during open the aird - I got the follow error message:

Representation version is: 15.0.0.202201261500
Last Sirius migration version is: 12.1.0.201708031200

Same situation for latest version of Lyo Designer, just last Sirius migration version has been change

What do I wrong?
Thanks!

**Comment by jad-elkhoury** [comment]
Hi

What version of lyoDesigner are you using?
Can you update it using the following update site https://download.eclipse.org/lyo/product/p2/edge ?

It might help, but another reason could be that I created these models using my local development version of LyoDesigner (which uses a newer version of libraries). I will check, and make sure the models are in synch with the public version of LyoDesinger.

But please ypdate your Lyodesigner anyway.

**Comment by Krusty84** [comment]
Dear @jad-elkhoury after update my problem has been solved, thank you very much!

**Comment by jad-elkhoury** [comment]
Great to hear @Krusty84 ! 
Just out of interest, are you working on the SySML2 specs? Or, just happened to find this repo?

**Comment by Krusty84** [comment]
> 

I am affiliated with MBSE, but I am fan of ARCADIA:), and I wanna create OSLC adapter for ARCADIA model
In the current situation I will use SysML v2 specs like a reference data

**Comment by jadelkhoury** [comment]
Hi @Krusty84 
You might have figured out that LyoDesigner is also based on Sirius, so it has much in common with ARCADIA/Capella.
I see you have also done done some work with Polarion/Teamcenter? 
Seems we have a lot in common. I'd be happy to connect and see if/how we can collaborate.
