### ISSUE TITLE
Intercax servers down

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/sysml-oslc-server#32]
<img width="557" alt="image" src="https://github.com/oslc-op/sysml-oslc-server/assets/64734/1248bbe9-25ea-4d89-a1d7-063a61b5732b">

@jadelkhoury we need an alternative method to populate the triplestore.

@jamsden CC

**Comment by jadelkhoury** [comment]
We can simply save the current triplestore in this project.
A good solution until we find a better source of SysML models.

**Comment by berezovskyi** [comment]
See #29 . It was something on my side, sorry.
