### ISSUE TITLE
How to use a specified sysmlv2 server?

### ISSUE THREAD

**Issue by sand7000** [oslc-op/sysml-oslc-server#35]
We would like to use a local sysmlv2 server. I think the sysmlv2 server used is specified in:

`org.oasis.oslcop.sysml.oslc-server/src/main/resources/jsonServer.properties`

to be:

```
jsonServerScheme=http
jsonServerHostname=sysml2-dev.intercax.com
jsonServerPort=9000
```

but I pushed the data in SysML2data.nq via postman as instructed while monitoring with wireshark and I see no traffic to any destination on port 9000. This is true whether I use the default value above or if I change to a local server IP. I can see the data via queries in the oslc swagger so things are working on that end, but as far as I can tell no data is not being transmitted to or from SysMLv2. I also do not see any of the data from SysML2data.nq when I do queries directly to the sysmlv2 server. 

I thought the fuseki docker image I had to start was being used as a bridge to populate a project in a sysmlv2 server. Is my understanding wrong or did I just miss a step or something?

**Comment by sand7000** [comment]
We got this figured out. We were loading data directly into fuseki via a put to:

http://localhost:3030/ds/data 

when we should have been populating fuskei by loading data into sysmlv2 and then navigating to:

http://localhost:8085/sysml_oslc_server/oslc/populate

**Comment by berezovskyi** [comment]
Great to hear!

@jadelkhoury sounds like a good input to update the README.

**Comment by Jad-el-khoury** [comment]
Good to hear @sand7000 !
If you think the README can be improved, please make suggestions. 
I am biased because I wrote the instructions, so I believe they are crystal clear :-)
